function [mean_d, max_d] = calc_distances(actualData,tgtData)
    % Usage: Calculate and find the mean and maximum distance between acgual and target rrays. 
    %   Calculate the mean and maximum distance between actual and target trajectories.
    %   using Euclidian calculation
    % Inputs:
        % actualData: the actual trajectory data
        % tgtData: trajectory generated by robotic device
    % Outputs:
        % mean_d: the calculated Euclidian mean distance between actual and target.
        % max_d: the maximum difference found between actual and target.

    % Calculate the distances between the trajectories at each point
    distances = sqrt(sum((actualData - tgtData).^2, 2));
    % Find the mean and max distances for the array 'distances'
    mean_d = mean(distances);
    max_d = max(distances);

end